version: '3.3'
services:

  db:
    image: postgres
    volumes:
      - ../resources/ambon-diaspora/postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  pgadmin:
    image: thajeztah/pgadmin4
    volumes:
    - ../resources/ambon-diaspora/pgadmin:/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - db

  web:
    build: .
    command: python /code/manage.py migrate --noinput
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
